version: '3'

services:

  web:
    container_name: web_container
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - SERVER_NAME=${SERVER_NAME}

        - XDEBUG_ENABLE=${XDEBUG_ENABLE}
        - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST}
        - XDEBUG_MODE=${XDEBUG_MODE}

        - APACHE_DOCUMENT_ROOT=${APACHE_DOCUMENT_ROOT}
        - APACHE_SERVER_ADMIN=${APACHE_SERVER_ADMIN}
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html
      - ./web/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db

  db:
    container_name: db_container
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      - PGDATA=/tmp
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
